config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


    root 'welcome#index'

    namespace :admin do
      resources :jobs do
        member do
          post :publish
          post :hide
        end

        resources :resumes
      end
    end

resources :jobs do
 resources :resumes
   collection do
      get :search
    end
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord

  validates :title, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :location, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}

  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }

  has_many :resumes

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def admin?
      is_admin
   end

   has_many :resumes

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin
  layout "admin"

  def publish
    @job = Job.find(params[:id])
    @job.publish!
    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!
    redirect_to :back
  end


  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "This Job already archived"
      redirect_to root_path
    end
  end


  def index
    @jobs = Job.all
    @jobs = @jobs.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to admin_jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden, :location)
  end
end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout 'admin'

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
     if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end

  def index
    @application = Application.find(params[:id])
    @jobs = @application.jobs.recent.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :validate_search_key, only: [:search]

  def show
    @job = Job.find(params[:id])

  end

  def index
  @jobs = case params[:order]
          when 'by_lower_bound'
            Job.published.order('wage_lower_bound DESC')
          when 'by_upper_bound'
            Job.published.order('wage_upper_bound DESC')
          else
            Job.published.recent
          end
   @jobs = @jobs.paginate(:page => params[:page], :per_page => 5)
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new(job_params)

      if @job.save
        redirect_to jobs_path
      else
        render :new
      end
    end


    def edit
      @job = Job.find(params[:id])
    end

    def search
      if @query_string.present?
        search_result = Job.ransack(@search_criteria).result(:distinct => true)
        @jobs = search_result.paginate(:page => params[:page], :per_page => 5 )
      end
    end


    protected

    def validate_search_key
      @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
      @search_criteria = search_criteria(@query_string)
    end


    def search_criteria(query_string)
      { :title_cont => query_string }
    end

    def update
      @job = Job.find(params[:id])
      if @job.update(job_params)
        redirect_to jobs_path
      else
        render :edit
      end
    end

    def destroy
      @job = Job.find(params[:id])

      @job.destroy

      redirect_to jobs_path
    end

    private

    def job_params
      params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden, :location)
    end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "成功提交履历"
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "Ruby 之家欢迎你！"
  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
      @resource ||= User.new
  end

  def resource_class
      User
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_highlight_content(job,query_string)
    excerpt_cont = excerpt(job.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end

  def render_job_status(job)
   if job.is_hidden
     content_tag(:span, "", :class => "fa fa-lock")
   else
     content_tag(:span, "", :class => "fa fa-globe")
   end
 end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :location %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>


  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="col-md-12">
  <div class="pull-right";>
    <%= link_to("Add a job", new_admin_job_path, :class => "btn btn-default" ) %>
  </div>


<br><br>

<table class="table table-boldered table-striped custab" >
    <thead>
        <tr>
            <td>职缺</td>
            <td>收到履历数量</td>
            <td>薪资下限</td>
            <td>薪资上限 </td>
            <td>工作地址</td>
            <td>管理选项 </td>
            <td>刊登时间 </td>
        </tr>
    </thead>

    <% @jobs.each do |job| %>
    <tr>

        <td>
            <%= render_job_status(job) %>
            <%= link_to(job.title, admin_job_path(job)) %>
        </td>
        <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %> </td>
        <td> <%= job.wage_lower_bound %> </td>
        <td> <%= job.wage_upper_bound %> </td>
        <td> <%= job.location %> </td>
        <td>
          <%= link_to edit_admin_job_path(job), :class => "btn btn-xs btn-info" do %><i class="fa fa-pencil"></i><% end %>
            <%= link_to admin_job_path(job), :method => :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure?" } do %><i class="fa fa-trash-o",></i><% end %>
            <% if job.is_hidden %>

             <%= link_to publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-success" do %><i class="fa fa-eye"></i><% end %>
        <% else %>
            <%= link_to hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning" do %><i class="fa fa-eye-slash"></i><% end %>
            <% end %>
        </td>
        <td>
            <%= job.created_at %>
        </td>
    </tr>
    <% end %>
</table>
</div>
<div class="text-center">
  <%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for [:admin,@job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :location %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
                <h3 class="panel-title">
                    <%= resume.user.email %>
                </h3>
            </div>

        </div>
    </div>
    <div class="panel-body">
        <div class="trix-content">
            <p> <%= simple_format(resume.content) %> </p>
        </div>

        <hr>

        <% if resume.attachment.present? %>
          <i class="fa fa-paperclip"> </i>
          <%= link_to("Download Resume", resume.attachment_url) %>
        <% else %>
           No Attachment
        <% end %>
    </div>

</div>

app/views/admin/resumes/index.html.erb
<h2> <%= @job.title %> - 履历列表 </h2>

<hr>
<%= render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_flashes.html.erb
<div class='row'>
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>
</div>

app/views/common/_footer.html.erb
<!--
<div class="row">
<footer class="flex-rw">

  <ul class="footer-list-top">
    <li>
      <h4 class="footer-list-header">About Pavilion</h4></li>
    <li><a href='/shop/about-mission' class="generic-anchor footer-list-anchor" itemprop="significantLink">GET TO KNOW US</a></li>
    <li><a href='/promos.html' class="generic-anchor footer-list-anchor" itemprop="significantLink">PROMOS</a></li>
    <li><a href='/retailers/new-retailers.html' class="generic-anchor footer-list-anchor" itemprop="significantLink">BECOME A RETAILER</a></li>

    <li><a href='/job-openings.html' itemprop="significantLink" class="generic-anchor footer-list-anchor">JOB OPENINGS</a></li>

    <li><a href='/shop/about-show-schedule' class="generic-anchor footer-list-anchor" itemprop="significantLink">EVENTS</a></li>
  </ul>
  <ul class="footer-list-top">
    <li>
      <h4 class="footer-list-header">The Gift Selection</h4></li>


    <li><a href='/Angels/cat/id/70' class="generic-anchor footer-list-anchor">ANGEL FIGURINES</a></li>
    <li><a href='/Home-Decor/cat/id/64' class="generic-anchor footer-list-anchor">HOME DECOR</a></li>
    <li><a href='/Mugs/cat/id/32' class="generic-anchor footer-list-anchor">MUGS</a></li>
    <li><a href='/Pet-Lover/cat/id/108' class="generic-anchor footer-list-anchor">PET LOVER</a></li>
    <li><a href='/Ladies-Accessories/cat/id/117' class="generic-anchor footer-list-anchor" target="_blank">HANDBAGS & JEWELRY</a></li>
  </ul>
  <ul class="footer-list-top">
    <li id='help'>
      <h4 class="footer-list-header">Please Help Me</h4></li>
    <li><a href='/shop/about-contact' class="generic-anchor footer-list-anchor" itemprop="significantLink">CONTACT</a></li>
    <li><a href='/faq.html' class="generic-anchor footer-list-anchor" itemprop="significantLink">FAQ</a></li>
    <li id='find-a-store'><a href='/shop/store-locator' class="generic-anchor footer-list-anchor" itemprop="significantLink">STORE LOCATOR</a></li>
    <li id='user-registration'><a href='/shop/user-registration?URL=' class="generic-anchor footer-list-anchor" itemprop="significantLink">NEW USERS</a></li>
    <li id='order-tracking'><a href='/shop/order-status' itemprop="significantLink" class="generic-anchor footer-list-anchor">ORDER STATUS</a></li>
  </ul>
  <section class="footer-social-section flex-rw">
    <span class="footer-social-overlap footer-social-connect">
      CONNECT <span class="footer-social-small">with</span> US
    </span>
    <span class="footer-social-overlap footer-social-icons-wrapper">
      <a href="http://www.pinterest.com/paviliongift/" class="generic-anchor" target="_blank" title="Pinterest" itemprop="significantLink"><i class="fa fa-pinterest"></i></a>
      <a href="https://www.facebook.com/paviliongift" class="generic-anchor" target="_blank" title="Facebook" itemprop="significantLink"><i class="fa fa-facebook"></i></a>
      <a href="https://twitter.com/PavilionGiftCo" class="generic-anchor" target="_blank" title="Twitter" itemprop="significantLink"><i class="fa fa-twitter"></i></a>
      <a href="http://instagram.com/paviliongiftcompany" class="generic-anchor" target="_blank" title="Instagram" itemprop="significantLink"><i class="fa fa-instagram"></i></a>
      <a href="https://www.youtube.com/channel/UCYgUODvd0qXbu_LkUWpTVEg" class="generic-anchor" target="_blank" title="Youtube" itemprop="significantLink"><i class="fa fa-youtube"></i></a>
      <a href="https://plus.google.com/+Paviliongift/posts" class="generic-anchor" target="_blank" title="Google Plus" itemprop="significantLink"><i class="fa fa-google-plus"></i></a>
      </span>
  </section>
  <section class="footer-bottom-section flex-rw">
    <div class="footer-bottom-wrapper">
      <i class="fa fa-copyright" role="copyright">

</i> 2015 Pavilion in <address class="footer-address" role="company address">Bergen, NY</address><span class="footer-bottom-rights"> - All Rights Reserved - </span>
    </div>
    <div class="footer-bottom-wrapper">
      <a href="/terms-of-use.html" class="generic-anchor" rel="nofollow">Terms</a> | <a href="/privacy-policy.html" class="generic-anchor" rel="nofollow">Privacy</a>
    </div>
  </section>
</footer>
</div> -->

<div class="row">
  <div class="footer">
      <p class="text-center">Copyright ©2017 Ruby 之家
          <br>Design by Liu Dezheng
      </p>
  </div>
</div>

  <!-- <footer class="footer">
      <div class="container">
          <div class="row">
              <div class="col-md-10 col-md-offset-1">
                <div class="row">
                  <div class="col-md-2 col-xs-4">
                    <h4>工作机会</h4>
                    <ul class="list-unstyled">
                      <li><a href="#s">求职专区</a></li>
                      <li><a href="#s">海外工作</a></li>
                      <li><a href="#s">兼职外包</a></li>
                    </ul>
                  </div>
                  <div class="col-md-2 col-xs-4">
                    <h4>企业资源</h4>
                    <ul class="list-unstyled">
                      <li><a href="#s">线下培训</a></li>
                      <li><a href="#s">联合招聘</a></li>
                      <li><a href="#s">加值服务</a></li>
                    </ul>
                  </div>
                  <div class="col-md-2 col-xs-4">
                    <h4>关于我们</h4>
                    <ul class="list-unstyled">
                      <li><a href="#s">公司介绍</a></li>
                      <li><a href="#s">常见问题</a></li>
                      <li><a href="#s">联系方式</a></li>
                    </ul>
                  </div>
                  <div class="col-md-6 col-xs-12 footer-box">
                    <div>
                      <a href="#s"><%= image_tag("link_facebook.png") %></a>
                      <a href="#s"><%= image_tag("link_google-plus.png") %></a>
                      <a href="#s"><%= image_tag("link_linkedin.png") %></a>
                      <a href="#s"><%= image_tag("link_twitter.png") %></a>
                    </div>
                    <div class="footer-content">
                      <%= image_tag("wechat.png") %> xbearx0516
                      <%= image_tag("slack.png") %> xbearx1987 <br />
                      <%= image_tag("logdown.png") %> http://xbearx1987-blog.logdown.com
                      <div class="goodjob">
                        <a href="https://fullstack.xinshengdaxue.com/works/288" target="_blank"><%= image_tag("thumbs-up.png") %></a>
                      </div>
                    </div>
                  </div>
                </div>
                  <hr />
                  <p>Designed By <a href="http://xbearx1987-blog.logdown.com/" target="_blank">Jimmy Wang</a> | Copyright ©2017 职赢网
              </div>
          </div>
      </div>
  </footer>
  Contact GitHub API Training Shop Blog About -->

app/views/common/_navbar.html.erb
<div class="row">
 <!-- navbar主体部分  -->
<nav class="navbar navbar-default" navbar-fixed-top role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><i class="fa fa-home " aria-hidden="true">  Ruby 之家</i></a> Listing </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                <li><a href="#" data-toggle="modal" data-target="#signup-modal">注册</a></li>
                <li><a href="#" data-toggle="modal" data-target="#login-modal">登录</a></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <% if current_user.admin? %>
                        <li> <%= link_to("Admin Panel", admin_jobs_path) %> </li>
                        <% end %>
                        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
 <!-- navbar主体部分  -->


<!-- navbar登陆弹窗部分  -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2>Log in</h2>
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :email, required: false, autofocus: true %>
           <%= f.input :password, required: false %>
           <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
         </div>
         <div class="form-actions">
           <%= f.button :submit, "Log in" %>
         </div>
       <% end %>
    </div>
  </div>
</div>
 <!-- navbar登陆弹窗部分  -->

 <!-- navbar搜索栏部分  -->
<div class="nav navbar-nav navbar-right">
  <%= form_tag search_jobs_path , :method => :get do %>
      <div class="input-group" id="search-id" >
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="请输入职位信息">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>

      </div>
      <% end %>
    </div>
<!-- navbar搜索栏部分  -->
<!--
navbar注册部分 -->

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h2>Sign up</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
 <!-- navbar注册部分  -->

app/views/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :location %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>


  <%= f.submit "Submit" %>
<% end %>

app/views/jobs/index.html.erb
<div class="col-md-10 col-centered">
<div class="panel panel-default">
    <div class="panel-heading">
      <h3>求职列表
      <div class="dropdown clearfix pull-right">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          排序
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
            <li>
              <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
            </li>
            <li>
                <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>

            </li>
            <li>
              <%= link_to("按照发表时间排序", jobs_path ) %>

            </li>
        </ul>
      </div>
   </h3>

    </div>
  <div class="panel-body">

    <table class="table table-boldered">
        <thead>
            <tr>

                <td>职缺</td>
                <td>薪资下限</td>
                <td>薪资上限</td>
                <td>工作地址</td>
                <td>刊登时间</td>
            </tr>

        </thead>
        <tbody>
            <% @jobs.each do |job| %>
            <tr>
                <td>
                    <%= link_to(job.title, job_path(job)) %>
                </td>
                <td>
                    <%= job.wage_lower_bound %>
                </td>
                <td>
                    <%= job.wage_upper_bound %>
                </td>
                <td>
                    <%= job.location %>
                </td>
                <td>
                    <%= job.created_at %>
                </td>
            </tr>
            <% end %>
        </tbody>

    </table>
  </div>
</div>
</div>
<div class="text-center">
  <%= will_paginate @jobs %>
</div>

app/views/jobs/new.html.erb
<div class="col-lg-10">
  <div class="panel panel-info">
    <div class="panel-heading">Add a job</div>
      <div class="panel-body">
        <%= simple_form_for @job do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :wage_lower_bound, :label => "薪资下限" %>
        <%= f.input :wage_upper_bound, :label => "薪资上限" %>
        <%= f.input :location %>
        <%= f.input :contact_email %>
        <%= f.input :is_hidden %>
        <%= f.submit "Submit", class: 'btn btn-success'%>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/search.html.erb
<div>
  <br>
<% if @query_string.blank? %>
    <div class="search-info-title">
      Sorry, The search content cannot be blank, please type some product into to search.
    </div>

  <% elsif @jobs.blank? %>
    <br>
    <h2 class="search-info-title">搜索信息不能为空，请输入关键字搜索</h2>
  <% else %>
    <h2 class="search-info-title"> 有关"<%= @query_string %>"的工作信息 </h2>
    <div class="search-result">

      <div class="row jobs-show0"></div>
      <div class="job-table">
        <% @jobs.each do |job| %>
        <div class="row jobs-show">

          <div class="col-md-12 col-lg-9 col-lg-offset-1">

            <div class="pull-right">
              发布时间：<%= job.created_at.to_date %>
            </div>
            <p ><%= link_to(render_highlight_content(job,@query_string),job_path(job)) %></p>

          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="text-center">
      <%= will_paginate(@jobs, renderer: BootstrapPagination::Rails) %>
    </div>
  <% end %>
</div>

app/views/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>

<div class="text-center">
  <%= link_to("投交履历", new_job_resume_path(@job), :style => "font-size: 30px; text-decoration:underline;") %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Job Listing </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <div class="content">
        <div class="container-fluid">
           <div class="row">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
                <ul class="nav nav-pills nav-stacked" style="max-width: 200px; padding-top:0px;">
                    <li class="active"><%= link_to("Jobs", admin_jobs_path ) %> </li>
                </ul>

              <div class="col-md-12">
                <%= yield %>
              </div>
           </div>
         </div>
           <div class="row">
          <%= render "common/footer" %>
          </div>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Ruby 之家 </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="shortcut icon" href="https://ooo.0o0.ooo/2017/04/28/590326a068a2a.png">
    </head>

    <body>
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
         </div>
        </div>
      </div>
        <%= render "common/footer" %>
    </body>
</html>